## Acceptance platform pipeline. 

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

resources:
 pipelines:
   - pipeline: gluupassport
     source: sign-in-canada.gluu-passport
   - pipeline: shiboxauthauthn3
     source: sign-in-canada.shib-oxauth-authn3

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  # define b as a counter with the prefix as variable a, and seed as 10.
  minor: $[counter(variables['major'], 10)]

steps:

- script: |
    ls -al $(Pipeline.Workspace)
    cd deployment/static/opt/gluu/jetty/oxauth/custom
    tar -czv --owner=root --group=root -f custom.tgz *
    mv custom.tgz $(Pipeline.Workspace)/s/deployment/static/opt/dist/signincanada
    cd $(Pipeline.Workspace)
    ls -al s/deployment/static/opt/dist/signincanada
    tar -tvf s/deployment/static/opt/dist/signincanada/custom.tgz
  displayName: 'Packaging UI'
  continueOnError: false

- script: |
    echo 'Downloading AppInsights SDK'
    wget https://github.com/microsoft/ApplicationInsights-Java/releases/download/2.5.1/applicationinsights-web-auto-2.5.1.jar \
       -P deployment/static/opt/dist/signincanada
    echo 'Downloading AppInsights Agent'
    wget https://github.com/microsoft/ApplicationInsights-Java/releases/download/2.5.1/applicationinsights-agent-2.5.1.jar \
       -P deployment/static/opt/azure
    ls -al 
  displayName: 'Downloading AppInsights'
  continueOnError: false

- script: |
    echo 'Downloading Latest Amazon Corretto'
    wget https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz \
      -P deployment/static/opt/dist/corretto
    wget https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz.sig \
      -P deployment/static/opt/dist/corretto
    echo 'Checking file integritiy'
    gpg --import deployment/static/opt/dist/corretto/B04F24E3.pub
    gpg deployment/static/opt/dist/corretto/amazon-corretto-8-x64-linux-jdk.tar.gz.sig
  displayName: 'Downloading Latest Amazon Corretto'
  continueOnError: false


- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7302639f-e704-47c3-9557-99b4e04a75bc'
    definition: '285'
    buildVersionToDownload: 'latest'
    artifactName: 'gluu-passport'
    targetPath: '$(Pipeline.Workspace)/s/deployment/static/opt/dist/gluu'
  displayName: 'Download gluu-passport tarballs'
  continueOnError: false

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7302639f-e704-47c3-9557-99b4e04a75bc'
    definition: '288'
    buildVersionToDownload: 'latest'
    artifactName: 'shib-oxauth-authn3'
    targetPath: '$(Pipeline.Workspace)/s/deployment/static/opt/dist/signincanada'
  displayName: 'Downloading shib-oxauth-authn3 libs'

- script: |
    cd deployment/static/opt/dist/signincanada
    mkdir shibjar && tar -C shibjar -xvf shib-oxauth-authn3-4.1.0.sic1.tar
    cp shibjar/shib-oxauth-authn3-4.1.0.sic1/edit-webapp/WEB-INF/lib/shib-oxauth-authn3-4.1.0.sic1.jar .
    rm -rf shib-oxauth-authn3-4.1.0.sic1.tar && rm -rf shib-oxauth-authn3-4.1.0.sic1.zip && rm -rf shibjar
    ls -al 
  displayName: 'Moving Shiboleth Jar'

- script: |
    cd deployment/static/opt/dist/gluu
    mv package/*gz .
    rm -rf package
    ls -al 
    cd $(Pipeline.Workspace)/s
  displayName: 'Moving gluu packages'
  continueOnError: true

- script: |
    cd deployment/static/
    echo 'packaging tarball'
    chmod 755 $(find . -type d -print)
    chmod 644 $(find . -type f -print)
    chmod 700 opt/dist/signincanada/postinstall.sh
    chmod 700 opt/dist/scripts/azure/keyvault.sh
    tar -czv --owner=root --group=root -f $(Build.ArtifactStagingDirectory)/SIC-AP-0.0.$(minor).tgz --exclude='opt/gluu' *
  displayName: 'Packaging tarball'
  continueOnError: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'acceptance-platform'
    publishLocation: 'pipeline'